// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChallengeInstructionsController from "./challenge_instructions_controller"
application.register("challenge-instructions", ChallengeInstructionsController)

import CodeController from "./code_controller"
application.register("code", CodeController)

import DashtabsController from "./dashtabs_controller"
application.register("dashtabs", DashtabsController)

import GameSubscriptionController from "./game_subscription_controller"
application.register("game-subscription", GameSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LpCardsController from "./lp_cards_controller"
application.register("lp-cards", LpCardsController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SolutionController from "./solution_controller"
application.register("solution", SolutionController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
