require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'bundle/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Rails/SkipsModelValidations:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/SpaceAroundOperators:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - puma_dev
    - test

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RedundantCopEnableDirective:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: align_brackets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

# Rails performance ####################################################################################################

Rails/FindById:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: true

Rails/HttpStatus:
  Enabled: true
  EnforcedStyle: symbolic

Rails/InverseOf:
  Enabled: true

Rails/LinkToBlank:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/Pick:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

########################################################################################################################

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false