name: Rails CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Set up Database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        TEST_DB_URL: "postgres://postgres:postgres@localhost:5432/teki_test"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/teki_test"
      run: |
        bin/rails db:create db:schema:load --trace
    - name: Run Rspec Tests
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        TEST_DB_URL: "postgres://postgres:postgres@localhost:5432/teki_test"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/teki_test"
      run: |
        bundle exec rspec
